language: node_js
node_js: "stable"
notifications:
  email: true
if: (type = push AND branch = master) OR (type = pull_request)
jobs:
  include:
    - stage: "merge templates"
    - script: 
      	- echo "build dir is ($TRAVIS_BUILD_DIR)"
	- cd $TRAVIS_BUILD_DIR/scripts && ProcessTemplates.cmd
