# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Template Warnings

on:
  pull_request:
  push:
    branches: master

jobs:
  validate:
        
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v4

    - name: Get changed files
      id: changed-workbook-files
      uses: tj-actions/changed-files@v44
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      with:
        # since_last_remote_commit: true
        files: |
            **.workbook
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.changed-workbook-files.outputs.any_changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run analyze '${{ steps.changed-workbook-files.outputs.all_changed_files }}'